version: 2.1


orbs:
  snyk: snyk/snyk@0.0.8


executors:
  python-js:
    docker:
      - image: circleci/python:3.7-node-browsers
    working_directory: ~/project


jobs:
  install:
    executor: python-js
    steps:
      - checkout
      - restore_cache:
          key: deps-{{ checksum "Pipfile.lock" }}-{{ checksum "package-lock.json" }}
      - run:
          name: install dependencies
          command: pipenv install --dev && npm install
      - save_cache:
          key: deps-{{ checksum "Pipfile.lock" }}-{{ checksum "package-lock.json" }}
          paths:
            - ~/.local/share/virtualenvs
            - ./node_modules
      - persist_to_workspace:
          root: "~"
          paths:
              - .local/share/virtualenvs
              - project/node_modules
              - project

  # needs $SNYK_TOKEN from https://app.snyk.io/account/
  security-scan:
    executor: python-js
    steps:
      - attach_workspace:
          at: "~"
      - snyk/scan:
          organization: honzajavorek
          project: junior.guru
          monitor-on-build: true
          target-file: package.json
      - snyk/scan:
          organization: honzajavorek
          project: junior.guru
          monitor-on-build: true
          target-file: Pipfile

  test:
    executor: python-js
    steps:
      - attach_workspace:
          at: "~"
      - run: pipenv run test -v

  # needs $GOOGLE_SERVICE_ACCOUNT
  fetch-build:
    executor: python-js
    steps:
      - attach_workspace:
          at: "~"
      - run: pipenv run fetch && pipenv run build
      - persist_to_workspace:
          root: "~"
          paths:
              - project/juniorguru/data
              - project/public
      - run: tar -cvzf public.tar.gz ./public
      - store_artifacts:
          path: ./public.tar.gz

  # needs $GOOGLE_SERVICE_ACCOUNT, $NOW_TOKEN, $NOW_ORG_ID, $NOW_PROJECT_ID
  # runs fetch & build
  deploy:
    executor: python-js
    steps:
      - attach_workspace:
          at: "~"
      - run:
          name: install 'now'
          command: sudo npm install --global --unsafe-perm now
      - run:
          name: deploy
          command: now --prod -t "$NOW_TOKEN"
      - persist_to_workspace:
          root: "~"
          paths:
              - project/juniorguru/data
              - project/public

  check-anchors:
    executor: python-js
    steps:
      - attach_workspace:
          at: "~"
      - run: pipenv run check-anchors

  check-links:
    executor: python-js
    steps:
      - attach_workspace:
          at: "~"
      - run: |
          # Internet is flaky... retrying 3 times to be sure the problem
          # is consistent - see https://unix.stackexchange.com/a/82602/43016
          n=0
          until [ $n -ge 3 ]
          do
            pipenv run check-links && break
            n=$[$n+1]
            sleep 5
          done


workflows:
  version: 2

  default_workflow:
    jobs:
      - install
      - test:
          requires:
            - install
      - fetch-build:
          requires:
            - install
      - check-anchors:
          requires:
            - fetch-build

  nightly_workflow:
    jobs:
      - install
      - security-scan:
          requires:
            - install
      - deploy:
          requires:
            - install
      - check-links:
          requires:
            - deploy
    triggers:
      - schedule:
          cron: "30 9 * * *"
          filters:
            branches:
              only:
                - master
