version: 2.1


executors:
  python-js:
    docker:
      - image: circleci/python:3.7-node-browsers
    working_directory: ~/project


jobs:
  install:
    executor: python-js
    steps:
      - checkout
      - restore_cache:  # caches npm deps based on whether the deps declaration has changed
          key: deps-{{ checksum "Pipfile.lock" }}-{{ checksum "package-lock.json" }}
      - run:
          name: install dependencies
          command: pipenv install --dev && npm install
      - save_cache:
          key: deps-{{ checksum "Pipfile.lock" }}-{{ checksum "package-lock.json" }}
          paths:
            - ~/.local/share/virtualenvs
            - ./node_modules
      - persist_to_workspace:
          root: "~"
          paths:
              - .local/share/virtualenvs
              - project/node_modules
              - project

  test:
    executor: python-js
    steps:
      - attach_workspace:
          at: "~"
      - run: pipenv run test -v

  # needs $GOOGLE_SERVICE_ACCOUNT
  fetch-build:
    executor: python-js
    steps:
      - attach_workspace:
          at: "~"
      - run: 'date +"%Y-%m-%d" > .today'  # saves today's date to a file so it can be used to expire cache
      - restore_cache:  # caches all HTTP communication of the scrapers for one day
          key: scrapy-{{ checksum ".today" }}
      - run: pipenv run fetch && pipenv run build
      - save_cache:
          key: scrapy-{{ checksum ".today" }}
          paths:
            - .scrapy
      - persist_to_workspace:
          root: "~"
          paths:
              - project/juniorguru/data
              - project/public
      - run: tar -cvzf backup.tar.gz ./juniorguru/data
      - store_artifacts:
          path: ./backup.tar.gz  # all data gets backed up as a CI artifact
      - run: tar -cvzf public.tar.gz ./public
      - store_artifacts:
          path: ./public.tar.gz  # the generated HTML is made available for download (used in the deploy job)

  # needs $NOW_TOKEN, $NOW_ORG_ID, $NOW_PROJECT_ID
  deploy:
    executor: python-js
    steps:
      - attach_workspace:
          at: "~"
      - restore_cache:  # caches a dummy file .deploy which lets the subsequent code to recognize whether the git ref has been already deployed to Now or not
          key: deploy-{{ .Revision }}
      - run:
          name: deploy
          command: |
            if [[ -f .deploy ]]; then
              echo "Looks like the build has been triggered by CircleCI (nightly, retries). Deploying with ZEIT Now CLI."
              sudo npm install --global --unsafe-perm now
              now --prod -t "$NOW_TOKEN"
            else
              echo "Looks like the build has been triggered by GitHub (there are no previous 'deploy' jobs for this commit). Skipping duplicate deploy with ZEIT Now CLI."
              echo "$CIRCLE_SHA1" > .deploy
            fi
      - save_cache:
          key: deploy-{{ .Revision }}
          paths:
            - .deploy

  check-anchors:
    executor: python-js
    steps:
      - attach_workspace:
          at: "~"
      - run: pipenv run check-anchors

  check-links:
    executor: python-js
    steps:
      - attach_workspace:
          at: "~"
      - run: pipenv run check-links --retry

  check-scrapers:
    executor: python-js
    steps:
      - attach_workspace:
          at: "~"
      - run: pipenv run check-scrapers

  check-performance:
    executor: python-js
    steps:
      - attach_workspace:
          at: "~"
      - run: pipenv run check-performance
      - run:
          command: tar -cvzf lighthouse.tar.gz ./lighthouse
          when: always
      - store_artifacts:
          path: ./lighthouse.tar.gz  # HTML and JSON reports from lighthouse


workflows:
  version: 2

  default_workflow:
    jobs:
      - install
      - test:
          requires:
            - install
      - fetch-build:
          requires:
            - install
      - check-anchors:
          requires:
            - fetch-build
      - check-scrapers:
          requires:
            - fetch-build
      - deploy:
          # This makes sure retries of 'master' builds still deploy,
          # even though they were not initiated by a GitHub push. Might
          # cause double deploy for builds initiated by GitHub push, but
          # the deploy job recognizes they're to be skipped.
          filters:
            branches:
              only:
                - master
          requires:
            - fetch-build
      - check-performance:
          requires:
            - deploy

  nightly_workflow:
    jobs:
      - install
      - fetch-build:
          requires:
            - install
      - deploy:
          requires:
            - fetch-build
      - check-scrapers:
          requires:
            - fetch-build
      - check-links:
          requires:
            - fetch-build
      - check-performance:
          requires:
            - deploy
    triggers:
      - schedule:
          cron: "0 4 * * *"
          filters:
            branches:
              only:
                - master
