version: 2.1


orbs:
  snyk: snyk/snyk@0.0.8


executors:
  python-js:
    docker:
      - image: circleci/python:3.7-node-browsers
    working_directory: ~/project


jobs:
  install:
    executor: python-js
    steps:
      - checkout
      - restore_cache:
          key: deps-{{ checksum "Pipfile.lock" }}-{{ checksum "package-lock.json" }}
      - run:
          name: install dependencies
          command: pipenv install --dev && npm install
      - save_cache:
          key: deps-{{ checksum "Pipfile.lock" }}-{{ checksum "package-lock.json" }}
          paths:
            - ~/.local/share/virtualenvs
            - ./node_modules
      - persist_to_workspace:
          root: "~"
          paths:
              - .local/share/virtualenvs
              - project/node_modules
              - project

  security-scan:  # needs $SNYK_TOKEN from https://app.snyk.io/account/
    executor: python-js
    steps:
      - attach_workspace:
          at: "~"
      - snyk/scan:
          organization: honzajavorek
          project: junior.guru
          monitor-on-build: true
          target-file: package.json
      - snyk/scan:
          organization: honzajavorek
          project: junior.guru
          monitor-on-build: true
          target-file: Pipfile

  test:
    executor: python-js
    steps:
      - attach_workspace:
          at: "~"
      - run: pipenv run test -v

  fetch-build:  # needs $GOOGLE_SERVICE_ACCOUNT
    executor: python-js
    steps:
      - attach_workspace:
          at: "~"
      - run: pipenv run fetch && pipenv run build
      - persist_to_workspace:
          root: "~"
          paths:
              - project/juniorguru/data
              - project/public
      - run: tar -cvzf public.tar.gz ./public
      - store_artifacts:
          path: ./public.tar.gz

  check-anchors:
    executor: python-js
    steps:
      - attach_workspace:
          at: "~"
      - run: pipenv run check-anchors

  check-links:
    executor: python-js
    steps:
      - attach_workspace:
          at: "~"
      - run: |
          # Internet is flaky... retrying 3 times to be sure the problem
          # is consistent - see https://unix.stackexchange.com/a/82602/43016
          n=0
          until [ $n -ge 3 ]
          do
            pipenv run check-links && break
            n=$[$n+1]
            sleep 5
          done


workflows:
  version: 2

  default_workflow: &default_workflow
    jobs:
      - install
      - security-scan:
          requires:
            - install
      - test:
          requires:
            - install
      - fetch-build:
          requires:
            - install
      - check-anchors:
          requires:
            - fetch-build
      - check-links:
          requires:
            - fetch-build

  nightly_workflow:
    <<: *default_workflow
    triggers:
      - schedule:
          cron: "*/5 * * * *"
          filters:
            branches:
              only:
                - master
