site_name: junior.guru
site_url: https://junior.guru/

theme:
  name: null
  custom_dir: 'theme/'

plugins:
  - macros
  # - mkdocs-simple-hooks:
  #     hooks:
  #       on_env: "juniorguru.mkdocs.hooks:on_env"

strict: true
