site_name: junior.guru
site_url: https://junior.guru/

nav:
  - Příručka: 'motivation/'
  - Práce: 'jobs/'
  - Klub: 'club/'  #'club.md'

theme:
  name: null
  custom_dir: theme/

plugins:
  - macros:
      include_dir: juniorguru/mkdocs/components/

# Removed 'strict' from mkdocs, because it gives warnings if linking non-existing targets. Once the Flask
# app is gone, 'strict' should return.
#strict: true
