site_name: junior.guru
site_url: https://junior.guru/

nav:
  - Příručka: 'motivation/'
  - Práce: 'jobs/'
  - Klub: 'club/'  #'club.md'

theme:
  name: null
  custom_dir: theme/

plugins:
  - mkdocs-simple-hooks:
      hooks:
        on_page_context: 'juniorguru.mkdocs.hooks:on_page_context'
        on_page_markdown: 'juniorguru.mkdocs.hooks:on_page_markdown'

# Removed 'strict' from mkdocs, because it gives warnings if linking non-existing targets. Once the Flask
# app is gone, 'strict' should return.
#strict: true
